# -*- coding: utf-8 -*-
"""gen ai task 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gme8nlEEVNOoaIAQyXzJhNg3RJil1Vi2
"""

# Install required libraries (if any)
# None needed for this basic Markov implementation

import random

# Sample text (you can replace this with any input)
sample_text = """
Machine learning is a field of artificial intelligence that uses statistical techniques
to give computer systems the ability to learn from data, without being explicitly programmed.
"""

# Step 1: Build the Markov Chain
def build_markov_chain(text, n=1):
    words = text.split()
    markov_chain = {}
    for i in range(len(words) - n):
        key = tuple(words[i:i+n])
        next_word = words[i+n]
        # Corrected the typo here from 'markv_chain' to 'markov_chain'
        if key not in markov_chain:
            markov_chain[key] = []
        markov_chain[key].append(next_word)
    return markov_chain

# Step 2: Generate Text
def generate_text(chain, n=1, max_words=50):
    key = random.choice(list(chain.keys()))
    generated_words = list(key)
    for _ in range(max_words):
        if key in chain:
            next_word = random.choice(chain[key])
            generated_words.append(next_word)
            key = tuple(generated_words[-n:])
        else:
            break
    return ' '.join(generated_words)

# Execution
n = 1  # You can try 2 or 3 for bigrams/trigrams
markov_chain = build_markov_chain(sample_text, n)
generated_text = generate_text(markov_chain, n)
print("Generated Text:")
print(generated_text)